#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pirana.Droid.Resource", IsApplication=true)]

namespace Pirana.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Pirana.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Pirana.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Pirana.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Pirana.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Pirana.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Pirana.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Pirana.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Pirana.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Pirana.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Pirana.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Pirana.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Pirana.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Pirana.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Pirana.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Pirana.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Pirana.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Pirana.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Pirana.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Pirana.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Pirana.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Pirana.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxBind = global::Pirana.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxDropDownItemTemplate = global::Pirana.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxGroupItemTemplate = global::Pirana.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxItemTemplate = global::Pirana.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxLang = global::Pirana.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxSource = global::Pirana.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplate = global::Pirana.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplateSelector = global::Pirana.Droid.Resource.Attribute.MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layoutManager = global::Pirana.Droid.Resource.Attribute.layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.reverseLayout = global::Pirana.Droid.Resource.Attribute.reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.spanCount = global::Pirana.Droid.Resource.Attribute.spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.stackFromEnd = global::Pirana.Droid.Resource.Attribute.stackFromEnd;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::Pirana.Droid.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::Pirana.Droid.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::Pirana.Droid.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvvmCrossTagId = global::Pirana.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvxBindingTagUnique = global::Pirana.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.item_touch_helper_previous_elevation = global::Pirana.Droid.Resource.Id.item_touch_helper_previous_elevation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding = global::Pirana.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxBind = global::Pirana.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxLang = global::Pirana.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl = global::Pirana.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl_MvxTemplate = global::Pirana.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView = global::Pirana.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Pirana.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView = global::Pirana.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView_MvxSource = global::Pirana.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView = global::Pirana.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Pirana.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxItemTemplate = global::Pirana.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView = global::Pirana.Droid.Resource.Styleable.MvxRecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector = global::Pirana.Droid.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView = global::Pirana.Droid.Resource.Styleable.RecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_descendantFocusability = global::Pirana.Droid.Resource.Styleable.RecyclerView_android_descendantFocusability;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_orientation = global::Pirana.Droid.Resource.Styleable.RecyclerView_android_orientation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_layoutManager = global::Pirana.Droid.Resource.Styleable.RecyclerView_layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_reverseLayout = global::Pirana.Droid.Resource.Styleable.RecyclerView_reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_spanCount = global::Pirana.Droid.Resource.Styleable.RecyclerView_spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_stackFromEnd = global::Pirana.Droid.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010018
			public const int ButtonPick = 2130771992;
			
			// aapt resource value: 0x7f010014
			public const int DisplayField = 2130771988;
			
			// aapt resource value: 0x7f010017
			public const int HideClear = 2130771991;
			
			// aapt resource value: 0x7f01001a
			public const int HideTime = 2130771994;
			
			// aapt resource value: 0x7f010015
			public const int Hint = 2130771989;
			
			// aapt resource value: 0x7f010005
			public const int MvxBind = 2130771973;
			
			// aapt resource value: 0x7f010009
			public const int MvxDropDownItemTemplate = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int MvxGroupItemTemplate = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int MvxItemTemplate = 2130771976;
			
			// aapt resource value: 0x7f010006
			public const int MvxLang = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public const int MvxSource = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int MvxTemplate = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int MvxTemplateSelector = 2130771972;
			
			// aapt resource value: 0x7f010019
			public const int ReadOnly = 2130771993;
			
			// aapt resource value: 0x7f010016
			public const int Stretch = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int TreeType = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int debugDraw = 2130771983;
			
			// aapt resource value: 0x7f01000c
			public const int horizontalSpacing = 2130771980;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010011
			public const int layout_horizontalSpacing = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int layout_newLine = 2130771984;
			
			// aapt resource value: 0x7f010012
			public const int layout_verticlSpacing = 2130771986;
			
			// aapt resource value: 0x7f01000e
			public const int orientation = 2130771982;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			// aapt resource value: 0x7f01000d
			public const int verticalSpacing = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_piranamobile = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_piranamobile = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_piranamobile = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_piranamobile = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_piranamobile = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_piranamobile = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int background_with_shadow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int blankperson = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_default_piranamobile = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_focused_piranamobile = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_cab_done_piranamobile = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_cab_done_pressed_piranamobile = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int button_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int button_enabled = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int button_focused = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int button_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int cab_background_bottom_piranamobile = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int cab_background_top_piranamobile = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int drawer_shadow_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int drawer_shadow_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_drawer_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_drawer_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int list_focused_piranamobile = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int list_pressed_piranamobile = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int menu_dropdown_panel_piranamobile = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int progress_bg_piranamobile = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int progress_horizontal_piranamobile = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int progress_primary_piranamobile = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int progress_secondary_piranamobile = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int selectable_background_piranamobile = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int shireborder = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int shirelogosmall = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int spinner_ab_default_piranamobile = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int spinner_ab_disabled_piranamobile = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int spinner_ab_focused_piranamobile = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int spinner_ab_pressed_piranamobile = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int spinner_background_ab_piranamobile = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int splash = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tab_indicator_ab_piranamobile = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int tab_selected_focused_piranamobile = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int tab_selected_piranamobile = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int tab_selected_pressed_piranamobile = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int tab_unselected_focused_piranamobile = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int tab_unselected_piranamobile = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int tab_unselected_pressed_piranamobile = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int MvvmCrossTagId = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int MvxBindingTagUnique = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int content_frame = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int demoImageView = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int drawer_layout = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int horizontal = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int left_drawer = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int txtMenu1 = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int txtMenu2 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int txtMenu3 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int txtMenu4 = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int vertical = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int drawerlistemptyitem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int drawerlistheaderitem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int drawerlistheaderitemwithimage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int drawerlistitem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int drawlistsubitem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FirstView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SplashScreen = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int drawer_close = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int drawer_open = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int ActionBar_Solid_Piranamobile = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ActionBar_Transparent_Piranamobile = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int ActionBarTabStyle_Piranamobile = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int ActionButton_CloseMode_Piranamobile = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int DropDownListView_Piranamobile = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int DropDownNav_Piranamobile = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int MyActionBarTabTextStyle = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int PiranaTheme = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int PopupMenu_Piranamobile = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int ProgressBar_Piranamobile = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Piranamobile = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int Theme_Piranamobile_Widget = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int Theme_YourTheme_Styled_ActionBar_TitleTextStyle = 2131099661;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlowLayout = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 3
			public const int FlowLayout_debugDraw = 3;
			
			// aapt resource value: 0
			public const int FlowLayout_horizontalSpacing = 0;
			
			// aapt resource value: 2
			public const int FlowLayout_orientation = 2;
			
			// aapt resource value: 1
			public const int FlowLayout_verticalSpacing = 1;
			
			public static int[] FlowLayout_LayoutParams = new int[] {
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 1
			public const int FlowLayout_LayoutParams_layout_horizontalSpacing = 1;
			
			// aapt resource value: 0
			public const int FlowLayout_LayoutParams_layout_newLine = 0;
			
			// aapt resource value: 2
			public const int FlowLayout_LayoutParams_layout_verticlSpacing = 2;
			
			public static int[] MvxBinding = new int[] {
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771978};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771979};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771976,
					2130771977};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] MvxRecyclerView = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public const int MvxRecyclerView_MvxTemplateSelector = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			public static int[] TreeControl = new int[] {
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 5
			public const int TreeControl_ButtonPick = 5;
			
			// aapt resource value: 1
			public const int TreeControl_DisplayField = 1;
			
			// aapt resource value: 4
			public const int TreeControl_HideClear = 4;
			
			// aapt resource value: 7
			public const int TreeControl_HideTime = 7;
			
			// aapt resource value: 2
			public const int TreeControl_Hint = 2;
			
			// aapt resource value: 6
			public const int TreeControl_ReadOnly = 6;
			
			// aapt resource value: 3
			public const int TreeControl_Stretch = 3;
			
			// aapt resource value: 0
			public const int TreeControl_TreeType = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
